title: "Deep Learning in the Frequency Domain: Advances, Challenges, and Applications for Time Series Analysis"
description: "2025 KDD Lecture-style Tutorial | Toronto, Canada <br/>
Kun Yi, Qi Zhang, Wei Fan, Longbing Cao, Shoujin Wang, Hui He, Guodong Long, Liang Hu, Qingsong Wen, Hui Xiong <br/>
Sunday, August 3, 2025 | 8:00 AM - 11:00 AM <br/>"
header_text: KDD 2025 Tutorial
theme: jekyll-theme-cayman
google_analytics: G-Y00QMX21NQ
